### PR TITLE
Unify postprocess signatures

### PR DESCRIPTION
**Pull request by furiosamg**
Some native postprocesses can only take one context at a time.
https://github.com/furiosa-ai/furiosa-models/blob/main/furiosa/models/client/api.py#L113-L116

Related TODOs, FIXMEs
- https://github.com/furiosa-ai/furiosa-models/blob/75199f782dfa48dcc404c6e0393968df3eca038f/furiosa/models/client/api.py#L113
- https://github.com/furiosa-ai/furiosa-models/blob/75199f782dfa48dcc404c6e0393968df3eca038f/furiosa/models/vision/ssd_mobilenet/__init__.py#L290

Others should take a sequence of contexts. So unify the signature

### CODE REVIEW

**Comment by furiosa-infra** [comment]
## Pip freeze result for ssd-resnet34
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.7.0
aiofiles==23.2.1
aiohttp==3.8.6
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.2.0
annotated-types==0.6.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
asttokens==2.4.1
async-timeout==4.0.3
asyncssh==2.14.1
atpublic==4.0
attrs==23.1.0
billiard==4.2.0
black==23.11.0
boto3==1.28.64
botocore==1.31.64
celery==5.3.5
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.7
colorama==0.4.6
comm==0.2.0
configobj==5.0.8
contourpy==1.2.0
cryptography==41.0.5
cycler==0.12.1
Cython==3.0.5
debugpy==1.8.0
decorator==5.1.1
dictdiffer==0.9.0
diskcache==5.6.3
distro==1.8.0
dpath==2.1.6
dulwich==0.21.6
dvc==3.30.0
dvc-data==2.21.2
dvc-http==2.30.2
dvc-objects==1.2.0
dvc-render==0.6.0
dvc-s3==2.23.0
dvc-studio-client==0.15.0
dvc-task==0.3.0
entrypoints==0.4
exceptiongroup==1.1.3
executing==2.0.1
fastjsonschema==2.19.0
filelock==3.13.1
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.45.0
frozenlist==1.4.0
fsspec==2023.10.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///workspace/source
furiosa-native-postprocess==0.9.0
furiosa-native-runtime==0.10.2
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.1
furiosa-runtime==0.10.0
gitdb==4.0.11
GitPython==3.1.40
grandalf==0.8
gto==1.5.0
hydra-core==1.3.2
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.1
iniconfig==2.0.0
ipykernel==6.27.0
ipython==8.17.2
isort==5.12.0
iterative-telemetry==0.0.8
jedi==0.19.1
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.20.0
jsonschema-specifications==2023.11.1
jupyter_client==8.6.0
jupyter_core==5.5.0
kiwisolver==1.4.5
kombu==5.3.3
lit==17.0.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.6
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
mypy-extensions==1.0.0
nbclient==0.6.8
nbformat==5.9.2
nbmake==1.4.6
nest-asyncio==1.5.8
networkx==3.2.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.1
opencv-python-headless==4.8.0.76
orjson==3.9.10
packaging==23.2
pandas==2.0.3
parso==0.8.3
pathspec==0.11.2
pexpect==4.8.0
Pillow==10.1.0
platformdirs==3.11.0
pluggy==1.3.0
prompt-toolkit==3.0.41
protobuf==4.25.1
psutil==5.9.6
ptyprocess==0.7.0
pure-eval==0.2.2
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.7
pycparser==2.21
pydantic==2.5.1
pydantic_core==2.14.3
pydot==1.4.2
pygit2==1.13.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.1.1
pytest==7.4.3
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
referencing==0.31.0
requests==2.31.0
rich==13.7.0
rpds-py==0.13.1
ruamel.yaml==0.18.5
ruamel.yaml.clib==0.2.8
ruff==0.1.5
s3fs==2023.10.0
s3transfer==0.7.0
scmrepo==1.4.1
semver==3.0.2
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.1
sqltrie==0.8.0
stack-data==0.6.3
sympy==1.12
tabulate==0.9.0
tokenize-rt==5.2.0
tomli==2.0.1
tomlkit==0.12.3
torch==2.0.1
torchvision==0.15.2
tornado==6.3.3
tqdm==4.66.1
traitlets==5.13.0
triton==2.0.0
typer==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.18
vine==5.1.0
voluptuous==0.14.0
wcwidth==0.2.10
wrapt==1.16.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.17.0
</pre></details>

**Comment by furiosa-infra** [comment]
## Pip freeze result for ssd-resnet34
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.7.0
aiofiles==23.2.1
aiohttp==3.8.6
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.2.0
annotated-types==0.6.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
asttokens==2.4.1
async-timeout==4.0.3
asyncssh==2.14.1
atpublic==4.0
attrs==23.1.0
billiard==4.2.0
black==23.11.0
boto3==1.28.64
botocore==1.31.64
celery==5.3.5
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.7
colorama==0.4.6
comm==0.2.0
configobj==5.0.8
contourpy==1.2.0
cryptography==41.0.5
cycler==0.12.1
Cython==3.0.5
debugpy==1.8.0
decorator==5.1.1
dictdiffer==0.9.0
diskcache==5.6.3
distro==1.8.0
dpath==2.1.6
dulwich==0.21.6
dvc==3.30.0
dvc-data==2.21.2
dvc-http==2.30.2
dvc-objects==1.2.0
dvc-render==0.6.0
dvc-s3==2.23.0
dvc-studio-client==0.15.0
dvc-task==0.3.0
entrypoints==0.4
exceptiongroup==1.1.3
executing==2.0.1
fastjsonschema==2.19.0
filelock==3.13.1
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.45.0
frozenlist==1.4.0
fsspec==2023.10.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///workspace/source
furiosa-native-postprocess==0.9.0
furiosa-native-runtime==0.10.2
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.1
furiosa-runtime==0.10.0
gitdb==4.0.11
GitPython==3.1.40
grandalf==0.8
gto==1.5.0
hydra-core==1.3.2
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.1
iniconfig==2.0.0
ipykernel==6.27.0
ipython==8.17.2
isort==5.12.0
iterative-telemetry==0.0.8
jedi==0.19.1
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.20.0
jsonschema-specifications==2023.11.1
jupyter_client==8.6.0
jupyter_core==5.5.0
kiwisolver==1.4.5
kombu==5.3.3
lit==17.0.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.6
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
mypy-extensions==1.0.0
nbclient==0.6.8
nbformat==5.9.2
nbmake==1.4.6
nest-asyncio==1.5.8
networkx==3.2.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.1
opencv-python-headless==4.8.0.76
orjson==3.9.10
packaging==23.2
pandas==2.0.3
parso==0.8.3
pathspec==0.11.2
pexpect==4.8.0
Pillow==10.1.0
platformdirs==3.11.0
pluggy==1.3.0
prompt-toolkit==3.0.41
protobuf==4.25.1
psutil==5.9.6
ptyprocess==0.7.0
pure-eval==0.2.2
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.7
pycparser==2.21
pydantic==2.5.1
pydantic_core==2.14.3
pydot==1.4.2
pygit2==1.13.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.1.1
pytest==7.4.3
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
referencing==0.31.0
requests==2.31.0
rich==13.7.0
rpds-py==0.13.1
ruamel.yaml==0.18.5
ruamel.yaml.clib==0.2.8
ruff==0.1.5
s3fs==2023.10.0
s3transfer==0.7.0
scmrepo==1.4.1
semver==3.0.2
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.1
sqltrie==0.8.0
stack-data==0.6.3
sympy==1.12
tabulate==0.9.0
tokenize-rt==5.2.0
tomli==2.0.1
tomlkit==0.12.3
torch==2.0.1
torchvision==0.15.2
tornado==6.3.3
tqdm==4.66.1
traitlets==5.13.0
triton==2.0.0
typer==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.18
vine==5.1.0
voluptuous==0.14.0
wcwidth==0.2.10
wrapt==1.16.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.17.0
</pre></details>

**Comment by furiosa-infra** [comment]
## Pip freeze result for ssd-resnet34
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.7.0
aiofiles==23.2.1
aiohttp==3.8.6
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.2.0
annotated-types==0.6.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
asttokens==2.4.1
async-timeout==4.0.3
asyncssh==2.14.1
atpublic==4.0
attrs==23.1.0
billiard==4.2.0
black==23.11.0
boto3==1.28.64
botocore==1.31.64
celery==5.3.5
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.7
colorama==0.4.6
comm==0.2.0
configobj==5.0.8
contourpy==1.2.0
cryptography==41.0.5
cycler==0.12.1
Cython==3.0.5
debugpy==1.8.0
decorator==5.1.1
dictdiffer==0.9.0
diskcache==5.6.3
distro==1.8.0
dpath==2.1.6
dulwich==0.21.6
dvc==3.30.0
dvc-data==2.21.2
dvc-http==2.30.2
dvc-objects==1.2.0
dvc-render==0.6.0
dvc-s3==2.23.0
dvc-studio-client==0.15.0
dvc-task==0.3.0
entrypoints==0.4
exceptiongroup==1.1.3
executing==2.0.1
fastjsonschema==2.19.0
filelock==3.13.1
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.45.0
frozenlist==1.4.0
fsspec==2023.10.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///workspace/source
furiosa-native-postprocess==0.9.0
furiosa-native-runtime==0.10.3
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.1
furiosa-runtime==0.10.0
gitdb==4.0.11
GitPython==3.1.40
grandalf==0.8
gto==1.5.0
hydra-core==1.3.2
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.1
iniconfig==2.0.0
ipykernel==6.27.0
ipython==8.17.2
isort==5.12.0
iterative-telemetry==0.0.8
jedi==0.19.1
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.20.0
jsonschema-specifications==2023.11.1
jupyter_client==8.6.0
jupyter_core==5.5.0
kiwisolver==1.4.5
kombu==5.3.3
lit==17.0.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.6
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
mypy-extensions==1.0.0
nbclient==0.6.8
nbformat==5.9.2
nbmake==1.4.6
nest-asyncio==1.5.8
networkx==3.2.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.1
opencv-python-headless==4.8.0.76
orjson==3.9.10
packaging==23.2
pandas==2.0.3
parso==0.8.3
pathspec==0.11.2
pexpect==4.8.0
Pillow==10.1.0
platformdirs==3.11.0
pluggy==1.3.0
prompt-toolkit==3.0.41
protobuf==4.25.1
psutil==5.9.6
ptyprocess==0.7.0
pure-eval==0.2.2
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.7
pycparser==2.21
pydantic==2.5.1
pydantic_core==2.14.3
pydot==1.4.2
pygit2==1.13.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.1.1
pytest==7.4.3
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
referencing==0.31.0
requests==2.31.0
rich==13.7.0
rpds-py==0.13.1
ruamel.yaml==0.18.5
ruamel.yaml.clib==0.2.8
ruff==0.1.5
s3fs==2023.10.0
s3transfer==0.7.0
scmrepo==1.4.1
semver==3.0.2
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.1
sqltrie==0.8.0
stack-data==0.6.3
sympy==1.12
tabulate==0.9.0
tokenize-rt==5.2.0
tomli==2.0.1
tomlkit==0.12.3
torch==2.0.1
torchvision==0.15.2
tornado==6.3.3
tqdm==4.66.1
traitlets==5.13.0
triton==2.0.0
typer==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.18
vine==5.1.0
voluptuous==0.14.0
wcwidth==0.2.10
wrapt==1.16.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.17.0
</pre></details>

**Comment by furiosa-infra** [comment]
## Pip freeze result for ssd-mobilenet
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.7.0
aiofiles==23.2.1
aiohttp==3.8.6
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.2.0
annotated-types==0.6.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
asttokens==2.4.1
async-timeout==4.0.3
asyncssh==2.14.1
atpublic==4.0
attrs==23.1.0
billiard==4.2.0
black==23.11.0
boto3==1.28.64
botocore==1.31.64
celery==5.3.5
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.7
colorama==0.4.6
comm==0.2.0
configobj==5.0.8
contourpy==1.2.0
cryptography==41.0.5
cycler==0.12.1
Cython==3.0.5
debugpy==1.8.0
decorator==5.1.1
dictdiffer==0.9.0
diskcache==5.6.3
distro==1.8.0
dpath==2.1.6
dulwich==0.21.6
dvc==3.30.0
dvc-data==2.21.2
dvc-http==2.30.2
dvc-objects==1.2.0
dvc-render==0.6.0
dvc-s3==2.23.0
dvc-studio-client==0.15.0
dvc-task==0.3.0
entrypoints==0.4
exceptiongroup==1.1.3
executing==2.0.1
fastjsonschema==2.19.0
filelock==3.13.1
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.45.0
frozenlist==1.4.0
fsspec==2023.10.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///workspace/source
furiosa-native-postprocess==0.9.0
furiosa-native-runtime==0.10.3
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.1
furiosa-runtime==0.10.0
gitdb==4.0.11
GitPython==3.1.40
grandalf==0.8
gto==1.5.0
hydra-core==1.3.2
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.1
iniconfig==2.0.0
ipykernel==6.27.0
ipython==8.17.2
isort==5.12.0
iterative-telemetry==0.0.8
jedi==0.19.1
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.20.0
jsonschema-specifications==2023.11.1
jupyter_client==8.6.0
jupyter_core==5.5.0
kiwisolver==1.4.5
kombu==5.3.3
lit==17.0.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.6
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
mypy-extensions==1.0.0
nbclient==0.6.8
nbformat==5.9.2
nbmake==1.4.6
nest-asyncio==1.5.8
networkx==3.2.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.1
opencv-python-headless==4.8.0.76
orjson==3.9.10
packaging==23.2
pandas==2.0.3
parso==0.8.3
pathspec==0.11.2
pexpect==4.8.0
Pillow==10.1.0
platformdirs==3.11.0
pluggy==1.3.0
prompt-toolkit==3.0.41
protobuf==4.25.1
psutil==5.9.6
ptyprocess==0.7.0
pure-eval==0.2.2
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.7
pycparser==2.21
pydantic==2.5.1
pydantic_core==2.14.3
pydot==1.4.2
pygit2==1.13.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.1.1
pytest==7.4.3
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
referencing==0.31.0
requests==2.31.0
rich==13.7.0
rpds-py==0.13.1
ruamel.yaml==0.18.5
ruamel.yaml.clib==0.2.8
ruff==0.1.5
s3fs==2023.10.0
s3transfer==0.7.0
scmrepo==1.4.1
semver==3.0.2
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.1
sqltrie==0.8.0
stack-data==0.6.3
sympy==1.12
tabulate==0.9.0
tokenize-rt==5.2.0
tomli==2.0.1
tomlkit==0.12.3
torch==2.0.1
torchvision==0.15.2
tornado==6.3.3
tqdm==4.66.1
traitlets==5.13.0
triton==2.0.0
typer==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.18
vine==5.1.0
voluptuous==0.14.0
wcwidth==0.2.10
wrapt==1.16.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.17.0
</pre></details>

**Comment by furiosa-infra** [comment]
44ce33b Fix resnet34 native postproc to handle batched
```

--------------------------------------------------------------------------------------------------------- benchmark: 2 tests ---------------------------------------------------------------------------------------------------------
Name (time in ms)                                                 Min                   Max                Mean              StdDev              Median                 IQR            Outliers      OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_ssd_resnet34_with_native_rust_pp_accuracy      39.2772 (1.0)      1,065.1337 (1.0)       52.9684 (1.0)       18.1899 (1.0)       51.8038 (1.0)        3.5529 (1.0)        45;283  18.8792 (1.0)        5000           1
test_mlcommons_ssd_resnet34_accuracy                         103.2417 (2.63)     1,983.7664 (1.86)     270.2896 (5.10)     101.7535 (5.59)     273.3315 (5.28)     100.1425 (28.19)     777;194   3.6997 (0.20)       5000           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

**Comment by furiosa-infra** [comment]
602a08e Unify model-agnostic inference codes
```

----------------------------------------------------------------------------------------------------- benchmark: 2 tests ----------------------------------------------------------------------------------------------------
Name (time in ms)                                                Min                 Max               Mean            StdDev             Median               IQR            Outliers      OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy     5.7596 (1.0)       55.5441 (1.0)      12.8606 (1.0)      6.8002 (1.0)       9.3538 (1.0)      5.7241 (1.0)       669;499  77.7570 (1.0)        5000           1
test_mlcommons_ssd_mobilenet_accuracy                         6.6666 (1.16)     207.6039 (3.74)     14.4744 (1.13)     6.9699 (1.02)     11.5263 (1.23)     5.7895 (1.01)      610;410  69.0877 (0.89)       5000           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

**Review by hyunsik — APPROVED** [review]
the patch looks good to me.

**Comment by furiosa-infra** [comment]
## Pip freeze result for all
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.7.0
aiofiles==23.2.1
aiohttp==3.8.6
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.2.0
annotated-types==0.6.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
asttokens==2.4.1
async-timeout==4.0.3
asyncssh==2.14.1
atpublic==4.0
attrs==23.1.0
billiard==4.2.0
black==23.11.0
boto3==1.28.64
botocore==1.31.64
celery==5.3.5
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.7
colorama==0.4.6
comm==0.2.0
configobj==5.0.8
contourpy==1.2.0
cryptography==41.0.5
cycler==0.12.1
Cython==3.0.5
debugpy==1.8.0
decorator==5.1.1
dictdiffer==0.9.0
diskcache==5.6.3
distro==1.8.0
dpath==2.1.6
dulwich==0.21.6
dvc==3.30.0
dvc-data==2.21.2
dvc-http==2.30.2
dvc-objects==1.2.0
dvc-render==0.6.0
dvc-s3==2.23.0
dvc-studio-client==0.15.0
dvc-task==0.3.0
entrypoints==0.4
exceptiongroup==1.1.3
executing==2.0.1
fastjsonschema==2.19.0
filelock==3.13.1
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.45.0
frozenlist==1.4.0
fsspec==2023.10.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///workspace/source
furiosa-native-postprocess==0.9.0
furiosa-native-runtime==0.10.3
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.1
furiosa-runtime==0.10.0
gitdb==4.0.11
GitPython==3.1.40
grandalf==0.8
gto==1.5.0
hydra-core==1.3.2
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.1
iniconfig==2.0.0
ipykernel==6.27.0
ipython==8.17.2
isort==5.12.0
iterative-telemetry==0.0.8
jedi==0.19.1
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.20.0
jsonschema-specifications==2023.11.1
jupyter_client==8.6.0
jupyter_core==5.5.0
kiwisolver==1.4.5
kombu==5.3.3
lit==17.0.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.8.2
matplotlib-inline==0.1.6
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
mypy-extensions==1.0.0
nbclient==0.6.8
nbformat==5.9.2
nbmake==1.4.6
nest-asyncio==1.5.8
networkx==3.2.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.1
opencv-python-headless==4.8.0.76
orjson==3.9.10
packaging==23.2
pandas==2.0.3
parso==0.8.3
pathspec==0.11.2
pexpect==4.8.0
Pillow==10.1.0
platformdirs==3.11.0
pluggy==1.3.0
prompt-toolkit==3.0.41
protobuf==4.25.1
psutil==5.9.6
ptyprocess==0.7.0
pure-eval==0.2.2
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.7
pycparser==2.21
pydantic==2.5.1
pydantic_core==2.14.3
pydot==1.4.2
pygit2==1.13.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.1.1
pytest==7.4.3
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
referencing==0.31.0
requests==2.31.0
rich==13.7.0
rpds-py==0.13.1
ruamel.yaml==0.18.5
ruamel.yaml.clib==0.2.8
ruff==0.1.5
s3fs==2023.10.0
s3transfer==0.7.0
scmrepo==1.4.1
semver==3.0.2
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.1
sqltrie==0.8.0
stack-data==0.6.3
sympy==1.12
tabulate==0.9.0
tokenize-rt==5.2.0
tomli==2.0.1
tomlkit==0.12.3
torch==2.0.1
torchvision==0.15.2
tornado==6.3.3
tqdm==4.66.1
traitlets==5.13.0
triton==2.0.0
typer==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==1.26.18
vine==5.1.0
voluptuous==0.14.0
wcwidth==0.2.10
wrapt==1.16.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.17.0
</pre></details>

**Comment by furiosamg** [comment]
@SunghwanShim Your feedbacks have been applied to https://github.com/furiosa-ai/furiosa-models/pull/180/files/ecbefc62d3d23615f57769910e706addc30d7631 :)

**Comment by furiosa-infra** [comment]
37d7392 Update changelog
```

---------------------------------------------------------------------------------------------------------- benchmark: 9 tests ----------------------------------------------------------------------------------------------------------
Name (time in ms)                                                  Min                   Max                Mean              StdDev              Median                 IQR            Outliers       OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_resnet50_accuracy                                1.5461 (1.0)        101.7156 (1.95)       8.7268 (1.0)        6.3377 (1.72)       6.4198 (1.0)        2.3973 (1.23)    6489;8420  114.5892 (1.0)       50000           1
test_efficientnetb0_accuracy                                    5.6015 (3.62)       448.0164 (8.61)      13.0095 (1.49)      11.5870 (3.14)      11.4502 (1.78)       2.3211 (1.19)    1188;3197   76.8667 (0.67)      50000           1
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy       5.7864 (3.74)        52.0347 (1.0)       12.9598 (1.49)       7.4387 (2.02)       9.0787 (1.41)       5.9511 (3.06)      691;559   77.1619 (0.67)       5000           1
test_efficientnetv2s_accuracy                                   7.0070 (4.53)       460.4745 (8.85)      16.2091 (1.86)      13.4078 (3.63)      14.1586 (2.21)       3.7221 (1.91)    1360;2640   61.6938 (0.54)      50000           1
test_mlcommons_ssd_mobilenet_accuracy                           7.5684 (4.90)       206.6725 (3.97)      11.8185 (1.35)       3.6902 (1.0)       10.7865 (1.68)       1.9480 (1.0)       785;930   84.6133 (0.74)       5000           1
test_yolov5m_accuracy                                           8.6135 (5.57)       231.0496 (4.44)      17.1106 (1.96)      11.5029 (3.12)      13.2100 (2.06)       6.4502 (3.31)    1029;1152   58.4432 (0.51)      10000           1
test_yolov5l_accuracy                                          11.7786 (7.62)       296.3861 (5.70)      16.5562 (1.90)       7.8130 (2.12)      15.1459 (2.36)       3.3557 (1.72)      274;427   60.4004 (0.53)      10000           1
test_mlcommons_ssd_resnet34_with_native_rust_pp_accuracy       42.5423 (27.52)      714.9725 (13.74)     53.4186 (6.12)      16.0444 (4.35)      51.9199 (8.09)       5.7343 (2.94)        23;40   18.7201 (0.16)       5000           1
test_mlcommons_ssd_resnet34_accuracy                          103.6502 (67.04)    1,785.3081 (34.31)    288.1985 (33.02)    106.4679 (28.85)    287.9950 (44.86)    105.8091 (54.32)     707;210    3.4698 (0.03)       5000           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

**Pull request merged**
