### PR TITLE
Update some .dvc files to point to proper artifacts

### LINKED ISSUE #119: Having dfg not onnx
Originally found by @ipkn-furiosa .

`mlcommons_ssd_mobilenet_v1_int8.onnx` file is not onnx file.

```
(models) [faster] root@mg-shin-npu-0:~/furiosa-models/furiosa/models/data# hexyl -n 16 mlcommons_ssd_mobilenet_v1_int8.onnx
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 64 66 67 b4 b7 63 f0 00 ┊ 01 01 0a 2b 08 01 12 27 │dfg××c×0┊••_+•••'│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
(models) [faster] root@mg-shin-npu-0:~/furiosa-models/furiosa/models/data# hexyl -n 16 mlcommons_ssd_mobilenet_v1_int8_truncated.onnx
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 08 08 12 0d 6a 61 73 6f ┊ 6e 5f 66 75 72 69 6f 73 │•••_jaso┊n_furios│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```

### PR DESCRIPTION
**Pull request by sukyoungjeong-furiosa**
fixes #119

### CODE REVIEW

**Comment by furiosa-infra** [comment]
f48d3dd Update accuracy
```

--------------------------------------------------------------------------------------------------------- benchmark: 8 tests ---------------------------------------------------------------------------------------------------------
Name (time in ms)                                                  Min                   Max                Mean             StdDev              Median                IQR            Outliers       OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_resnet50_with_native_pp_accuracy                 3.3069 (1.0)         61.6055 (2.05)       6.8261 (1.0)       1.4277 (1.0)        6.6342 (1.0)       0.6907 (1.0)     4051;4493  146.4967 (1.0)       50000           1
test_mlcommons_resnet50_accuracy                                3.5087 (1.06)       120.9615 (4.02)       7.4410 (1.09)      1.6675 (1.17)       7.1960 (1.08)      1.1817 (1.71)    5601;3074  134.3912 (0.92)      50000           1
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy       5.4306 (1.64)       134.1215 (4.45)       7.5008 (1.10)      2.0821 (1.46)       7.2486 (1.09)      0.8107 (1.17)      217;324  133.3197 (0.91)       5000           1
test_yolov5m_accuracy                                           8.4460 (2.55)       213.3517 (7.08)      12.9748 (1.90)      4.3191 (3.03)      12.4832 (1.88)      1.9081 (2.76)      220;373   77.0727 (0.53)      10000           1
test_mlcommons_ssd_mobilenet_accuracy                           9.2058 (2.78)        30.1156 (1.0)       13.0871 (1.92)      2.3404 (1.64)      12.4507 (1.88)      2.2341 (3.23)      994;330   76.4114 (0.52)       5000           1
test_yolov5l_accuracy                                          11.5266 (3.49)       126.1822 (4.19)      16.5913 (2.43)      3.0355 (2.13)      16.1138 (2.43)      2.3502 (3.40)     1115;441   60.2724 (0.41)      10000           1
test_mlcommons_ssd_resnet34_with_native_rust_pp_accuracy      108.4740 (32.80)      572.2050 (19.00)    131.8598 (19.32)    12.4317 (8.71)     132.9316 (20.04)    11.3293 (16.40)      913;64    7.5838 (0.05)       5000           1
test_mlcommons_ssd_resnet34_accuracy                          170.2804 (51.49)    1,076.6570 (35.75)    238.2537 (34.90)    31.2329 (21.88)    233.6793 (35.22)    22.4588 (32.52)     736;403    4.1972 (0.03)       5000           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

**Comment by furiosa-infra** [comment]
```

--------------------------------------------------------------------------------------------------------- benchmark: 8 tests ---------------------------------------------------------------------------------------------------------
Name (time in ms)                                                  Min                   Max                Mean             StdDev              Median                IQR            Outliers       OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_resnet50_accuracy                                2.6941 (1.0)         51.9206 (5.78)       4.4261 (1.0)       0.9341 (3.65)       4.4275 (1.0)       0.1190 (1.0)    2791;11933  225.9328 (1.0)       50000           1
test_mlcommons_resnet50_with_native_pp_accuracy                 2.7276 (1.01)        52.4432 (5.83)       4.5002 (1.02)      0.9430 (3.68)       4.4772 (1.01)      0.1687 (1.42)   3029;11140  222.2122 (0.98)      50000           1
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy       4.4856 (1.67)         8.9895 (1.0)        5.1333 (1.16)      0.2562 (1.0)        5.0950 (1.15)      0.2877 (2.42)      1091;72  194.8049 (0.86)       5000           1
test_mlcommons_ssd_mobilenet_accuracy                           7.2813 (2.70)        11.9362 (1.33)       8.2019 (1.85)      0.4443 (1.73)       8.1006 (1.83)      0.4328 (3.64)      880;238  121.9226 (0.54)       5000           1
test_yolov5m_accuracy                                           7.5702 (2.81)        18.4592 (2.05)       8.7252 (1.97)      0.7701 (3.01)       8.5342 (1.93)      0.9229 (7.76)     2449;327  114.6099 (0.51)      10000           1
test_yolov5l_accuracy                                          10.0158 (3.72)        24.8067 (2.76)      11.0864 (2.50)      0.7502 (2.93)      10.9305 (2.47)      0.7917 (6.65)     1915;333   90.2006 (0.40)      10000           1
test_mlcommons_ssd_resnet34_with_native_rust_pp_accuracy      108.6617 (40.33)      432.1804 (48.08)    113.6638 (25.68)     7.2172 (28.17)    113.1800 (25.56)     3.7219 (31.28)       18;18    8.7979 (0.04)       5000           1
test_mlcommons_ssd_resnet34_accuracy                          135.3306 (50.23)    1,059.4433 (117.85)   162.3072 (36.67)    28.2768 (110.38)   158.9556 (35.90)    12.6395 (106.23)    140;168    6.1612 (0.03)       5000           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

**Comment by furiosa-infra** [comment]
```

--------------------------------------------------------------------------------------------------------- benchmark: 8 tests ---------------------------------------------------------------------------------------------------------
Name (time in ms)                                                  Min                   Max                Mean             StdDev              Median                IQR            Outliers       OPS            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_resnet50_with_native_pp_accuracy                 2.7218 (1.0)         48.4291 (6.27)       4.5360 (1.02)      0.9512 (3.69)       4.5095 (1.01)      0.1719 (1.25)   3065;11399  220.4597 (0.98)      50000           1
test_mlcommons_resnet50_accuracy                                2.7595 (1.01)        59.6207 (7.72)       4.4543 (1.0)       0.9527 (3.70)       4.4534 (1.0)       0.1375 (1.0)    2786;11226  224.5044 (1.0)       50000           1
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy       4.3436 (1.60)         7.7193 (1.0)        4.8242 (1.08)      0.2577 (1.0)        4.7626 (1.07)      0.2667 (1.94)      966;162  207.2887 (0.92)       5000           1
test_mlcommons_ssd_mobilenet_accuracy                           7.1524 (2.63)        12.6892 (1.64)       8.0223 (1.80)      0.4114 (1.60)       7.9313 (1.78)      0.3789 (2.76)      863;279  124.6520 (0.56)       5000           1
test_yolov5m_accuracy                                           7.2934 (2.68)        16.4406 (2.13)       8.5558 (1.92)      0.7769 (3.02)       8.3757 (1.88)      0.9458 (6.88)     2525;305  116.8804 (0.52)      10000           1
test_yolov5l_accuracy                                          10.0958 (3.71)        24.1524 (3.13)      11.1707 (2.51)      0.7071 (2.74)      11.0155 (2.47)      0.7815 (5.68)     2143;354   89.5202 (0.40)      10000           1
test_mlcommons_ssd_resnet34_with_native_rust_pp_accuracy      110.8075 (40.71)      477.7730 (61.89)    116.5803 (26.17)     8.1117 (31.48)    116.4472 (26.15)     1.6647 (12.11)       8;231    8.5778 (0.04)       5000           1
test_mlcommons_ssd_resnet34_accuracy                          131.9744 (48.49)    1,064.1727 (137.86)   162.7512 (36.54)    31.3156 (121.54)   158.9698 (35.70)    13.0393 (94.85)     142;190    6.1443 (0.03)       5000           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

**Comment by sukyoungjeong-furiosa** [comment]
@furiosamg , could you confirm that `mlcommons_ssd_mobilenet_v1_int8.onnx`, `mlcommons_ssd_resnet34_int8.onnx` have been correctly fixed?

**Review by furiosamg — APPROVED** [review]
Yes I can say two files are correct onnx now.
```
(base) [fix_119] root@mg-shin-npu-0:~/furiosa-models# onnx inspect furiosa/models/data/mlcommons_ssd_mobilenet_v1_int8.onnx
  Graph name: 16
  Graph inputs: 449
  Graph outputs: 12
  Nodes in total: 60
  ValueInfo in total: 48
  Initializers in total: 448
  Sparse Initializers in total: 0
  Quantization in total: 0
(base) [fix_119] root@mg-shin-npu-0:~/furiosa-models# onnx inspect furiosa/models/data/mlcommons_ssd_resnet34_int8.onnx
  Graph name: 7
  Graph inputs: 439
  Graph outputs: 12
  Nodes in total: 119
  ValueInfo in total: 107
  Initializers in total: 438
  Sparse Initializers in total: 0
  Quantization in total: 0
```


It seems like the accuracy may have been changed. If so, could you please update the corresponding documentations?
Thanks for you contribution.

**Comment by sukyoungjeong-furiosa** [comment]
Thanks for the review.

> It seems like the accuracy may have been changed. If so, could you please update the corresponding documentations? Thanks for you contribution.

The accuracy has been updated but remains unchanged when rounded to nearest 0.001. I'll leave it as now.

**Pull request merged**
